TOPIC:-JAVA LANG PACKAGE
--------
VIDEO NO=2
-----------
NUMBER OF PICTURES=NULL
------------------
VIDEO COMPLETED=YES 
-----------------(ALL FINISHED BUT JUST GO THROUGH ONCE AGAIN )

IMPORTANT EXAMPLES:-
--------------------
Example=7
Example=10
----------------->START OF EXAMPLES<---------------------------
Example=1
=========
NOTE:-
-----
PROGRAME=1
=========
EXPLANATION:-
============
hashcode() method.


Hashcode represents address of an Object  -->Wrong
we can override the hashcode method of an Object class,and keep our own number.--->Right.

But people will say hashcode represent address of Object,

But we can override hashcode method,so hashcode doesn t repesent address of an Object..
Bcoz we cannot overrride address of an Object.

Hashcode and adreess Both are different..

In java its imposssible to know the address of an object and size of an Object.
Bcoz java laungage is programmer friendly laungage not machine friedly laungage..

Memory level and machine level communication java won t provide much support...

In low level laungages like c or c++ we can know the address of 
an Object and size of an Object,they are
machine friendly laungages..


Hashcode does nt represent address of an Object.

hashcode is not address wat is it....?
  For every Object created in java a unique number generated by JVM is called hashcode.


  If hashcode is  not an address then wat s that unique number..? and where it is used...?
       We have hashing related data structure are there 
          .i e HashMap
               Hashtable
               HashSet

PAGE 133 LONG BOOK SEE THE DIAGRAM..
             
In hashing related data structure while saving an Object JVM generates an hascode(Unique Number) and uses it..
  i.e For every Object created in java JVM will genearate a Hahcode and Based on that Hashcode
      number JVM is gonna place that Object in the corresponding Bucket..

Ex:-If an Student Object is created its hashcode is 100,JVM is gonna palce that Student Object in 100 bucket.
			
		The reason for generating hashcode is searching will be very easy.
		Suppose assume i wana Search Student object,so immediately student Object hashcode is obtained and
		its searched in the corresponding Bucket..



Number 1 search algorithm upto today is hashing..

Some other search algorithm are 
linear search
Binary search.


comparing both linear search, Binary search and showing how hashing algorithm is efficient..

Linear Search algorithm:-
-------------------------
We have a requiremt like we have to search Ravi in our class,

See page upto 137 for explanation for hashing related explanation.



DP:-For every object a unique number generated by JVM which is nothing but hashcode,
Hashcode won t represent of Object.
JVM will use Hashcode while saving Objects into Hashing related data structures like 
HashMap
Hashtable
HashSet

the main advantage of saving objects based on hashcode is search operation will become easy.
(The most powerfull search algorithm upto today is Hashing).



Suppose we are not overriding hashcode() method,then Object class hashcode method() will be generated..

hashcode() method implementation in Object class..?

		public native int hashCode(); //its a native method, so see we can override native methods.

		how internally Object class hashcode () mehtod will generate hashcode..?
                          Based on address of Object only...
						     sir u told hashcode won t represent address..?
							       Yes hashcode won t represent address of an Object.
              hashcode is generated based on address but it does nt mean its an address..

			  ex:-Student Object address is 1234
 			         hashcode formula :- =(int)(Object address )*5+96*96+-98547+ some algorithm 
                                         = (int)((1234)*5+96*96+-98547 +some algorithm.
                                         =132 is generated hashcode..

									 hashcode generated based on Object address...
									 But hashcode is not address.

If we are giving chance to hashcode() method of Object class to execute then
Object class hashcode() method generates hashcode Based on Object address.
But generated hashcode is not Address of an Object.

Based on our requirement 
If we want we can override hashcode () method in our class to generates our own hashcode..


Overriding hashcode() method  is possible and its valid...

Overriding hashcode () method  which is the best time....?
         when overriding hashcode() a unique number should be generated,then it is said to be valid..See Example 2 
***************************-----END of--->1<--------***************************
Example=2
=========
NOTE:-
-----
PROGRAME=2
=========
EXPLANATION:-
============
Invalid hashcode overriding:-
-----------------------------
Case1:- See page 138 on long book.(Diagram)
-------
class Student
{
	.
	.
	.
	.
	.
	.
	.

	public int hashcode()
	{
	
	   return 100
	}
}

Invalid overriding coz for every Student Object generated hashcode is same.
It is improper way of overriding hashcode,coz for every  Student Object we are generating the same hashcode..
-------------------------------------------------------------------------------------------

Valid hashcode overriding:-
---------------------------
class Student
{
    .
	.
	.
	.
	.
	.
	.
	public int hashcode()
	{
	
	   return Rollno;
	}
}

Valid for every student Object a separate rollno will be generated..

overriding of hashcode method is said to be valid.
if and only if we generate a unique number as hashcode for every object.

It is a valid case of overriding hashcode bcoz we are generating a different hashcode for every Object..


wat is hashcode...?
A unique number generated by JVM based on address of corresponding Object is called hashcode

who is generating hashcode...?
JVM

wat is the advantage of generating hashcode....?
It s used in hashing related algorithm to place the corresoponding object in the specific bucket..

Is it possible to override hashcode method in Object class...?
YES

which is the proper way of overriding hashcode...?
When ever we are getting a unique number for every object created that is called as proper way of overriding 
hashcode..
***************************-----END of--->2<--------***************************
Example=3
=========
NOTE:-
-----
PROGRAME=3
=========
EXPLANATION:-
============
Relatinon between toString() and Haschcode() method..


  toString() method implemented in Object class
  --------------------------------------------
  1)When we calling/giving chance to Object class toString() method internally Object class
    hashcode method will be executed.

   public String toString() 
     {
        return getClass().getName() + "@" + Integer.toHexString(hashCode());
    }

	Overriding toString() meethod in student class 
	---------------------------------------------

	1)When we calling/giving chance to our overriding toString() method it
	  may not call Object class hashcode() method.

	public String toString() 
     {
        return return name+""+rollno;
    }
***************************-----END of--->3<--------***************************
Example=4
=========
NOTE:-
-----
PROGRAME=4
=========
EXPLANATION:-
============
Difference between toString() and hashcode() method
---------------------------------------------------

toString() vs hashcode()
------------------------
1)If we are giving a chance to Object class toString() method ,it will internally calls hashcode method
2)If we are overriding toString() method then our toString() method may not call hashcode() method.


***************************-----END of--->4<--------***************************
Example=5
=========
NOTE:-
-----
Some last programe not  related to this topic..

PROGRAME=5
=========
import java.util.*;
class Test
{

public String toString()
	{
          
		  return "Test";
    }
	public static void main(String [] args)
	{
		String s =new String("Vinay");
		System.out.println(s);
        Integer i=new Integer(10);
        System.out.println(i);

		ArrayList al =new ArrayList();
		al.add("abc");
		al.add(123456);
        System.out.println(al);



		Test t=new Test();
		System.out.println(t);
	}
}


C:\Users\DELL\Desktop>javac Test.java
Note: Test.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

C:\Users\DELL\Desktop>java Test
Vinay
10
[abc, 123456]
Test

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->5<--------***************************
Example=6
=========
NOTE:-
-----
Continuation of Example 5:-

PROGRAME=6
=========
class Test
{
	int i;
	Test(int i)
	{
	  this.i=i;
    }
	public static void main(String [] args)
	{
		Test t=new Test(10);
		Test t1=new Test(10);
		System.out.println(t);
		System.out.println(t1);
	}
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
Test@15db9742
Test@6d06d69c

EXPLANATION:-
============
In this programe we are not overrriding toString() method so Object class toString() method will be callled
so Object class toString() method interanlly calls Object class hashcode () method.


Page 139 long book see the equation..

Object class ==>toString()
                   ||
Object class ==>hashcode()
***************************-----END of--->6<--------***************************
Example=7
=========
NOTE:-
-----
Important Point and conclusion:-
--------------------------------
Here some important conclusion we are writing wrong method name 
hashCode--->Correct
hashcode--->Wrong


class Test extends Object
{
	/*so object class toString () method is present in Test class
	so Object class toString() method pesent in Test class calls hashCode () method 
	      (1) Frist it will see any hashcode method is there is Test class,if its there it will use
          	    Test class hashcode method if its not there then Object class hashcode method will be 
				executed*/
				            
}

PROGRAME=7
=========
class Test
{
	int i;
	Test(int i)
	{
	  this.i=i;
    }

	public int hashcode()
	{
	    return i;
	}
	public static void main(String [] args)
	{
        System.out.println("main");
		Test t=new Test(10);
		Test t1=new Test(100);
		System.out.println(t);
		System.out.println(t1);
	}
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main
Test@15db9742
Test@6d06d69c

C:\Users\DELL\Desktop>

EXPLANATION:-
============

In this example we u think we are overriding hashcode but we are not overriding it.
coz we are taking wrong spelling mistatke we  are creating a new method by name hashcode.



See Example 10:-
----------------
***************************-----END of--->7<--------***************************
Example=8
=========

NOTE:-
-----
Some important constructor concept came into me see the constructor 
this.name=this.name both side am using the same...
So am getting the null output..

PROGRAME=8
=========
class Test
{
	int i;
	String name;
	Test(int i,String name)
	{
	  this.i=i;
	  this.name=this.name;  // Observe here...
    }

	public int hashcode()
	{
	    return i;
	}

	public String toString()
	{
		return i+"---"+name;
	}
	public static void main(String [] args)
	{
        System.out.println("Main method ");
		Test t=new Test(10,"Vinay");
		Test t1=new Test(100,"Shetty");
		System.out.println(t);
		System.out.println(t1);
	}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
Main method
10---null
100---null

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->8<--------***************************
Example=9
=========
NOTE:-
-----
PROGRAME=9
=========
class Test
{
	int i;
	String name;
	Test(int i,String name)
	{
	  this.i=i;
	  this.name=name;
    }

	public int hashcode()
	{
	    return i;
	}

	public String toString()
	{
		return i+"---"+name;  //number + String =String only.,,
		                      //return i; //--->invalid 
	}
	public static void main(String [] args)
	{
        System.out.println("Main method 132 ");
		Test t=new Test(10,"Vinay");
		Test t1=new Test(100,"Shetty");
		System.out.println(t);
		System.out.println(t1);
	}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
Main method 132
10---Vinay
100---Shetty

C:\Users\DELL\Desktop>

EXPLANATION:-
============
In this Test class toString() method will be called and it won t call hashcode method..
Wheather we are writing hashcode() method or not it won t matter..
***************************-----END of--->9<--------***************************
Example=10
=========
NOTE:-
-----
In Test class extends Object class by default so Object class toString() method will be avaliable for
Test class..
so When ever we are calling toString() method present in Test class of Object class,
Frist it will check any hashcode method will
be present in Test class,if its there then Test class hashcode method will be executed.If not Object class hashcode()
method will be executed..



class Object
{
   	toString() {call hashcode() method}
	hashCode(){}
}
class Test extends Object
{
       toString() {call hashcode() method}
	   //It will check any hashCode method is there in Test class.if its not there then Object class hashcode method will
       //be executed
}


PROGRAME=10
=========
class Test
{
	int i;
	Test(int i)
	{
	  this.i=i;
    }

	public int hashCode()
	{
	    return i;
	}
	public static void main(String [] args)
	{
        System.out.println("Hello vinay 147");
		Test t=new Test(10);
		Test t1=new Test(100);
		System.out.println(t);
		System.out.println(t1);
	}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
Hello vinay 147
Test@a
Test@64

C:\Users\DELL\Desktop>

EXPLANATION:-
============
1)Which toString () method will be called...?
        Object class toString() method will be called..

		Object class toString() method internally calls hashcode method ..?
		         Which hashcode () method will be called...?
				           Test class hashcode method will be called..


In this example hashcode method is there in Test class so Test class hashCode method will be executed...
If hashcode () method is not there in Test class then Object class hashcode method will be executed..


conclusion:-Its like giving more preference to local methods Frist...


Explanation long book--->141 page

Test@a
Test@64


We are getting a same output If we run this on 1000 machines..
***************************-----END of--->10<--------***************************
Example=11
=========
NOTE:-
-----
PROGRAME=11
=========
EXPLANATION:-
============
DP:-If we are giving the chance to Object class toString() method internally it calls hashcode method.
If we are giving a chance to our own toString() method it may not call hashcode method..


vinay Point:-
1)If we are giving the chance to Object class toString() method internally it calls
overriding hashcode method in that corresponding class.
If overriding hashcode method is not there in corresponding class then Object  class hashCode() method
will be executed..

***************************-----END of--->11<--------***************************
Example=12
=========
NOTE:-
-----
PROGRAME=12
=========
EXPLANATION:-
============
***************************-----END of--->12<--------***************************
Example=13
=========
NOTE:-
-----
PROGRAME=13
=========
EXPLANATION:-
============
***************************-----END of--->13<--------***************************
Example=14
=========
NOTE:-
-----
PROGRAME=14
=========
EXPLANATION:-
============
***************************-----END of--->14<--------***************************
Example=15
=========
NOTE:-
-----
PROGRAME=15
=========
EXPLANATION:-
============
***************************-----END of--->15<--------***************************
Example=16
=========
NOTE:-
-----
PROGRAME=16
=========
EXPLANATION:-
============
***************************-----END of--->16<--------***************************
Example=17
=========
NOTE:-
-----
PROGRAME=17
=========
EXPLANATION:-
============
***************************-----END of--->17<--------***************************
Example=18
=========
NOTE:-
-----
PROGRAME=18
=========
EXPLANATION:-
============
***************************-----END of--->18<--------***************************
Example=19
=========
NOTE:-
-----
PROGRAME=19
=========
EXPLANATION:-
============
***************************-----END of--->19<--------***************************
Example=20
=========
NOTE:-
-----
PROGRAME=20
=========
EXPLANATION:-
============
***************************-----END of--->20<--------***************************
Example=21
=========
NOTE:-
-----
PROGRAME=21
=========
EXPLANATION:-
============
***************************-----END of--->21<--------***************************
Example=22
=========
NOTE:-
-----
PROGRAME=22
=========
EXPLANATION:-
============
***************************-----END of--->22<--------***************************
Example=23
=========
NOTE:-
-----
PROGRAME=23
=========
EXPLANATION:-
============
***************************-----END of--->23<--------***************************
Example=24
=========
NOTE:-
-----
PROGRAME=24
=========
EXPLANATION:-
============
***************************-----END of--->24<--------***************************
Example=25
=========
NOTE:-
-----
PROGRAME=25
=========
EXPLANATION:-
============
***************************-----END of--->25<--------***************************
Example=26
=========
NOTE:-
-----
PROGRAME=26
=========
EXPLANATION:-
============
***************************-----END of--->26<--------***************************
Example=27
=========
NOTE:-
-----
PROGRAME=27
=========
EXPLANATION:-
============
***************************-----END of--->27<--------***************************
Example=28
=========
NOTE:-
-----
PROGRAME=28
=========
EXPLANATION:-
============
***************************-----END of--->28<--------***************************
Example=29
=========
NOTE:-
-----
PROGRAME=29
=========
EXPLANATION:-
============
***************************-----END of--->29<--------***************************
Example=30
=========
NOTE:-
-----
PROGRAME=30
=========
EXPLANATION:-
============
***************************-----END of--->30<--------***************************
Example=31
=========
NOTE:-
-----
PROGRAME=31
=========
EXPLANATION:-
============
***************************-----END of--->31<--------***************************
Example=32
=========
NOTE:-
-----
PROGRAME=32
=========
EXPLANATION:-
============
***************************-----END of--->32<--------***************************
Example=33
=========
NOTE:-
-----
PROGRAME=33
=========
EXPLANATION:-
============
***************************-----END of--->33<--------***************************
Example=34
=========
NOTE:-
-----
PROGRAME=34
=========
EXPLANATION:-
============
***************************-----END of--->34<--------***************************
Example=35
=========
NOTE:-
-----
PROGRAME=35
=========
EXPLANATION:-
============
***************************-----END of--->35<--------***************************
Example=36
=========
NOTE:-
-----
PROGRAME=36
=========
EXPLANATION:-
============
***************************-----END of--->36<--------***************************
Example=37
=========
NOTE:-
-----
PROGRAME=37
=========
EXPLANATION:-
============
***************************-----END of--->37<--------***************************
Example=38
=========
NOTE:-
-----
PROGRAME=38
=========
EXPLANATION:-
============
***************************-----END of--->38<--------***************************
Example=39
=========
NOTE:-
-----
PROGRAME=39
=========
EXPLANATION:-
============
***************************-----END of--->39<--------***************************
Example=40
=========
NOTE:-
-----
PROGRAME=40
=========
EXPLANATION:-
============
***************************-----END of--->40<--------***************************
Example=41
=========
NOTE:-
-----
PROGRAME=41
=========
EXPLANATION:-
============
***************************-----END of--->41<--------***************************
Example=42
=========
NOTE:-
-----
PROGRAME=42
=========
EXPLANATION:-
============
***************************-----END of--->42<--------***************************
Example=43
=========
NOTE:-
-----
PROGRAME=43
=========
EXPLANATION:-
============
***************************-----END of--->43<--------***************************
Example=44
=========
NOTE:-
-----
PROGRAME=44
=========
EXPLANATION:-
============
***************************-----END of--->44<--------***************************
Example=45
=========
NOTE:-
-----
PROGRAME=45
=========
EXPLANATION:-
============
***************************-----END of--->45<--------***************************
Example=46
=========
NOTE:-
-----
PROGRAME=46
=========
EXPLANATION:-
============
***************************-----END of--->46<--------***************************
Example=47
=========
NOTE:-
-----
PROGRAME=47
=========
EXPLANATION:-
============
***************************-----END of--->47<--------***************************
Example=48
=========
NOTE:-
-----
PROGRAME=48
=========
EXPLANATION:-
============
***************************-----END of--->48<--------***************************
Example=49
=========
NOTE:-
-----
PROGRAME=49
=========
EXPLANATION:-
============
***************************-----END of--->49<--------***************************
Example=50
=========
NOTE:-
-----
PROGRAME=50
=========
EXPLANATION:-
============
***************************-----END of--->50<--------***************************
Example=51
=========
NOTE:-
-----
PROGRAME=51
=========
EXPLANATION:-
============
***************************-----END of--->51<--------***************************
Example=52
=========
NOTE:-
-----
PROGRAME=52
=========
EXPLANATION:-
============
***************************-----END of--->52<--------***************************
Example=53
=========
NOTE:-
-----
PROGRAME=53
=========
EXPLANATION:-
============
***************************-----END of--->53<--------***************************
Example=54
=========
NOTE:-
-----
PROGRAME=54
=========
EXPLANATION:-
============
***************************-----END of--->54<--------***************************
Example=55
=========
NOTE:-
-----
PROGRAME=55
=========
EXPLANATION:-
============
***************************-----END of--->55<--------***************************
Example=56
=========
NOTE:-
-----
PROGRAME=56
=========
EXPLANATION:-
============
***************************-----END of--->56<--------***************************
Example=57
=========
NOTE:-
-----
PROGRAME=57
=========
EXPLANATION:-
============
***************************-----END of--->57<--------***************************
Example=58
=========
NOTE:-
-----
PROGRAME=58
=========
EXPLANATION:-
============
***************************-----END of--->58<--------***************************
Example=59
=========
NOTE:-
-----
PROGRAME=59
=========
EXPLANATION:-
============
***************************-----END of--->59<--------***************************
Example=60
=========
NOTE:-
-----
PROGRAME=60
=========
EXPLANATION:-
============
***************************-----END of--->60<--------***************************
Example=61
=========
NOTE:-
-----
PROGRAME=61
=========
EXPLANATION:-
============
***************************-----END of--->61<--------***************************
Example=62
=========
NOTE:-
-----
PROGRAME=62
=========
EXPLANATION:-
============
***************************-----END of--->62<--------***************************
Example=63
=========
NOTE:-
-----
PROGRAME=63
=========
EXPLANATION:-
============
***************************-----END of--->63<--------***************************
Example=64
=========
NOTE:-
-----
PROGRAME=64
=========
EXPLANATION:-
============
***************************-----END of--->64<--------***************************
Example=65
=========
NOTE:-
-----
PROGRAME=65
=========
EXPLANATION:-
============
***************************-----END of--->65<--------***************************
Example=66
=========
NOTE:-
-----
PROGRAME=66
=========
EXPLANATION:-
============
***************************-----END of--->66<--------***************************
Example=67
=========
NOTE:-
-----
PROGRAME=67
=========
EXPLANATION:-
============
***************************-----END of--->67<--------***************************
Example=68
=========
NOTE:-
-----
PROGRAME=68
=========
EXPLANATION:-
============
***************************-----END of--->68<--------***************************
Example=69
=========
NOTE:-
-----
PROGRAME=69
=========
EXPLANATION:-
============
***************************-----END of--->69<--------***************************
Example=70
=========
NOTE:-
-----
PROGRAME=70
=========
EXPLANATION:-
============
***************************-----END of--->70<--------***************************
Example=71
=========
NOTE:-
-----
PROGRAME=71
=========
EXPLANATION:-
============
***************************-----END of--->71<--------***************************
Example=72
=========
NOTE:-
-----
PROGRAME=72
=========
EXPLANATION:-
============
***************************-----END of--->72<--------***************************
Example=73
=========
NOTE:-
-----
PROGRAME=73
=========
EXPLANATION:-
============
***************************-----END of--->73<--------***************************
Example=74
=========
NOTE:-
-----
PROGRAME=74
=========
EXPLANATION:-
============
***************************-----END of--->74<--------***************************
Example=75
=========
NOTE:-
-----
PROGRAME=75
=========
EXPLANATION:-
============
***************************-----END of--->75<--------***************************
Example=76
=========
NOTE:-
-----
PROGRAME=76
=========
EXPLANATION:-
============
***************************-----END of--->76<--------***************************
Example=77
=========
NOTE:-
-----
PROGRAME=77
=========
EXPLANATION:-
============
***************************-----END of--->77<--------***************************
Example=78
=========
NOTE:-
-----
PROGRAME=78
=========
EXPLANATION:-
============
***************************-----END of--->78<--------***************************
Example=79
=========
NOTE:-
-----
PROGRAME=79
=========
EXPLANATION:-
============
***************************-----END of--->79<--------***************************
Example=80
=========
NOTE:-
-----
PROGRAME=80
=========
EXPLANATION:-
============
***************************-----END of--->80<--------***************************
Example=81
=========
NOTE:-
-----
PROGRAME=81
=========
EXPLANATION:-
============
***************************-----END of--->81<--------***************************
Example=82
=========
NOTE:-
-----
PROGRAME=82
=========
EXPLANATION:-
============
***************************-----END of--->82<--------***************************
Example=83
=========
NOTE:-
-----
PROGRAME=83
=========
EXPLANATION:-
============
***************************-----END of--->83<--------***************************
Example=84
=========
NOTE:-
-----
PROGRAME=84
=========
EXPLANATION:-
============
***************************-----END of--->84<--------***************************
Example=85
=========
NOTE:-
-----
PROGRAME=85
=========
EXPLANATION:-
============
***************************-----END of--->85<--------***************************
Example=86
=========
NOTE:-
-----
PROGRAME=86
=========
EXPLANATION:-
============
***************************-----END of--->86<--------***************************
Example=87
=========
NOTE:-
-----
PROGRAME=87
=========
EXPLANATION:-
============
***************************-----END of--->87<--------***************************
Example=88
=========
NOTE:-
-----
PROGRAME=88
=========
EXPLANATION:-
============
***************************-----END of--->88<--------***************************
Example=89
=========
NOTE:-
-----
PROGRAME=89
=========
EXPLANATION:-
============
***************************-----END of--->89<--------***************************
Example=90
=========
NOTE:-
-----
PROGRAME=90
=========
EXPLANATION:-
============
***************************-----END of--->90<--------***************************
Example=91
=========
NOTE:-
-----
PROGRAME=91
=========
EXPLANATION:-
============
***************************-----END of--->91<--------***************************
Example=92
=========
NOTE:-
-----
PROGRAME=92
=========
EXPLANATION:-
============
***************************-----END of--->92<--------***************************
Example=93
=========
NOTE:-
-----
PROGRAME=93
=========
EXPLANATION:-
============
***************************-----END of--->93<--------***************************
Example=94
=========
NOTE:-
-----
PROGRAME=94
=========
EXPLANATION:-
============
***************************-----END of--->94<--------***************************
Example=95
=========
NOTE:-
-----
PROGRAME=95
=========
EXPLANATION:-
============
***************************-----END of--->95<--------***************************
Example=96
=========
NOTE:-
-----
PROGRAME=96
=========
EXPLANATION:-
============
***************************-----END of--->96<--------***************************
Example=97
=========
NOTE:-
-----
PROGRAME=97
=========
EXPLANATION:-
============
***************************-----END of--->97<--------***************************
Example=98
=========
NOTE:-
-----
PROGRAME=98
=========
EXPLANATION:-
============
***************************-----END of--->98<--------***************************
Example=99
=========
NOTE:-
-----
PROGRAME=99
=========
EXPLANATION:-
============
***************************-----END of--->99<--------***************************
Example=100
=========
NOTE:-
-----
PROGRAME=100
=========
EXPLANATION:-
============
***************************-----END of--->100<--------***************************
