TOPIC:-MULTITHREADING
--------
VIDEO NO=4
-----------
NUMBER OF PICTURES=1
------------------
1---------->(H:\JAVA NOTES\DURGA JAVA NOTES\MULTI THREADING\MULTI_THREADING_VIDEO_4)
VIDEO COMPLETED=YES
-----------------

IMPORTANT EXAMPLES:-
-------------------
Example=14
(5*)
----------------->START OF EXAMPLES<---------------------------
Example=1
=========
NOTE:-
-----
PROGRAME=1
=========
EXPLANATION:-
============
Every Thread in java has some priority it may be default priority generated by
JVM (or) explicitly customized provided by the programmer.
***************************-----END of--->1<--------***************************
Example=2
=========
NOTE:-
-----
PROGRAME=2
=========
EXPLANATION:-
============
(16:00)
Thread priority 
Example 
Traffic Signal near using 
minister,cm,pm,president,
***************************-----END of--->2<--------***************************
Example=3
=========
NOTE:-
-----
PROGRAME=3
=========
EXPLANATION:-
============
Thread  class defines the following methods to set and get priority.

1. public final int getPriority()
2. public final void setPriority(int newPriority);/

In notes they have written like this we can write like this also.

2. public final void setPriority(int x);//the allowed values are 1 to 10

t.setPriority(7);//(valid)
t.setPriority(17);//(Invalid)--->Illeagl Argument Exception.(Run Time Exception)
***************************-----END of--->3<--------***************************
Example=4
=========
NOTE:-
-----
PROGRAME=4
=========
 class MyThread extends Thread
{

}

class Test
{
	public static void main(String[] args)
	{
	   System.out.println("MAIN THREAD PRIORITY="+Thread.currentThread().getPriority()); //5
	   MyThread t=new MyThread(); 
	   System.out.println("Child Thread Priority="+t.getPriority());
	}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
MAIN THREAD PRIORITY=5
Child Thread Priority=5

C:\Users\DELL\Desktop>

EXPLANATION:-
============
Default Priority :-

Default Priority only for main Thread is 5.
But for all remaining Thread s default Priority will be inherited from Parent to Child.
That is wat ever Priority Parent Thread has same Priority will be there for the Child Thread.


Case 2:-
--------

***************************-----END of--->4<--------***************************
Example=5
=========
NOTE:-
-----
PROGRAME=5
=========
 class MyThread extends Thread
{

}

class Test
{
	public static void main(String[] args)
	{
	   System.out.println("MAIN THREAD PRIORITY="+Thread.currentThread().getPriority()); //5
	   Thread.currentThread().setPriority(9); //setting main Thread priority.

       MyThread t=new MyThread();//instatiating new Thread
                                 // i.e Child Thread
       System.out.println("MAIN THREAD PRIORITY AFTER CHANGING="+Thread.currentThread().getPriority()); 
	   System.out.println("Child Thread Priority="+t.getPriority());
	}
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
MAIN THREAD PRIORITY=5
MAIN THREAD PRIORITY AFTER CHANGING=9
Child Thread Priority=9

C:\Users\DELL\Desktop>
EXPLANATION:-
============
Parent class and Child class Concept is different.
Parent Thread and Child Therad Concept is differnt.

Parent Thread--->main Thread
Child Thread---->Thread created by main Thread.

MyThread t=new MyThread();  --->Which Thread executes this line is Parent.
***************************-----END of--->5<--------***************************
Example=6
=========
NOTE:-
-----
General Error:-

PROGRAME=6
=========
class MyThread extends Thread
{

}

class Test
{
	public static void main(String[] args)
	{
	   System.out.println("MAIN THREAD PRIORITY="+Thread.currentThread().getPriority()); 
	   System.out.println(Thread.currentThread().setPriority(9)); 
	   
	   MyThread t=new MyThread();
       System.out.println("MAIN THREAD PRIORITY AFTER CHANGING="+Thread.currentThread().getPriority()); 
	   System.out.println("Child Thread Priority="+t.getPriority());
	}
}


C:\Users\DELL\Desktop>javac Test.java
Test.java:11: error: 'void' type not allowed here
           System.out.println(Thread.currentThread().setPriority(9));
                                                                ^
1 error

C:\Users\DELL\Desktop>
EXPLANATION:-
============
Thread.currentThread().setPriority(9)

setPriority(9) return type is void so we can t use inside sop statements.
***************************-----END of--->6<--------***************************
Example=7
=========
NOTE:-
-----
PROGRAME=7
=========

 class MyThread extends Thread
{

}

class Test
{
	public static void main(String[] args)
	{
	   System.out.println("MAIN THREAD PRIORITY="+Thread.currentThread().getPriority()); //5
	   Thread.currentThread().setPriority(17); 

       MyThread t=new MyThread();//instatiating new Thread
                                 // i.e Child Thread
       System.out.println("MAIN THREAD PRIORITY AFTER CHANGING="+Thread.currentThread().getPriority()); 
	   System.out.println("Child Thread Priority="+t.getPriority());
	}
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
MAIN THREAD PRIORITY=5
Exception in thread "main" java.lang.IllegalArgumentException
        at java.lang.Thread.setPriority(Thread.java:1086)
        at Test.main(Test.java:11)

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->7<--------***************************
Example=8
=========
NOTE:-
-----
PROGRAME=8
=========
class MyThread extends Thread
{
            public void run()
	{     
            System.out.println("Run method executed by "+Thread.currentThread().getName()); 

	}
}

class Test
{
	public static void main(String[] args)
	{
	   System.out.println("MAIN THREAD "+Thread.currentThread().getName()); 
	   new MyThread().run();
    }
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
MAIN THREAD main
Run method executed by main

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->8<--------***************************
Example=9
=========
NOTE:-
-----
PROGRAME=9
=========
class MyThread extends Thread{}
class Test
{
	public static void main(String[] args)
	{System.out.println("main method--->"+Thread.currentThread().getName());}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method--->main

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->9<--------***************************
Example=10
=========
NOTE:-
-----
SEE THIS CONCEPT FOR STATIC BLOCK USING 1.6 VERSION WHERE MAIN METHOD() IS NOT COMPULASARY.. 

PROGRAME=10
=========
class MyThread extends Thread
{
   public void run()
	{
       System.out.println("Mythread run method--->"+Thread.currentThread().getName());
	}
}
class Test
{
	public static void main(String[] args)
	{
		MyThread t=new MyThread();
		t.start();
       System.out.println("main method--->"+Thread.currentThread().getName());
	}
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method--->main
Mythread run method--->Thread-0

C:\Users\DELL\Desktop>

EXPLANATION:-
============

System.out.println("main method--->"+Thread.currentThread().getName());
This line is written in main method,so which Thread is responsible to invoke this main method
main Thread is responsible so we are gettnig as ---->main

System.out.println("main method--->"+Thread.currentThread().getName());
This line is written in class MyThread--> run() method,so which Thread is responsible to invoke this run() method
Thread-0 is responsible for invoking this method so its called we are getting as ---->Thread-0.



System.out.println("main method--->"+Thread.currentThread().getName());
So where this line is written for that method which is the corresponding invoking Thread,that Thread name is given.


***************************-----END of--->10<--------***************************
Example=11
=========
NOTE:-
-----
PROGRAME=11
=========
class A 
{
	void m1() 
	{
	      System.out.println("A class m1 mehtod-->"+Thread.currentThread().getName());
		  new B().m1();
	 }
}
    class B
    {
    	void m1()
			{
			System.out.println("B class m1 mehtod-->"+Thread.currentThread().getName());
			new C().m1();
			}
    }
   
    class C
   {
	   void m1()
	   {
        System.out.println("C class m1 mehtod-->"+Thread.currentThread().getName());
        }
   }

class Test
   {
     public static void main(String[] args)
    {
      System.out.println("main mehtod ="+Thread.currentThread().getName());
      new A().m1();
    }
}
    

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main mehtod =main
A class m1 mehtod-->main
B class m1 mehtod-->main
C class m1 mehtod-->main

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->11<--------***************************
Example=12
=========
NOTE:-
-----
How Thread s are getting the names..

PROGRAME=12
=========
class A extends Thread
{
	void m1() 
	{
	      System.out.println("A class m1 mehtod-->"+Thread.currentThread().getName());
		  new B().m1();
	 }

	 public void run()
		 {
	        System.out.println("A class RUN()mehtod-->"+Thread.currentThread().getName());
          }
}
    class B
    {
    	void m1()
			{
			System.out.println("B class m1 mehtod-->"+Thread.currentThread().getName());
			new C().m1();
			}
    }
   
    class C
   {
	   void m1()
	   {
        System.out.println("C class m1 mehtod-->"+Thread.currentThread().getName());
        }
   }

class Test
   {
     public static void main(String[] args)
    {
      System.out.println("main mehtod ="+Thread.currentThread().getName());
      new A().m1();
	  new A().start();
    }
}
    



C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main mehtod =main
A class m1 mehtod-->main
B class m1 mehtod-->main
C class m1 mehtod-->main
A class RUN()mehtod-->Thread-1

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->12<--------***************************
Example=13
=========
NOTE:-
-----
Allocating names to Thread.How each Thread is gettin the name..

PROGRAME=13
=========
 class MyThread extends Thread
{
	void m1() 
	{
	      MyThread t=new MyThread();
	      System.out.println("t--->"+t.getName()); //2 --->5
	      
	      MyThread t1=new MyThread();
	      System.out.println("t1--->"+t1.getName());//3 --->6
	      System.out.println("MyThread m1"+Thread.currentThread().getName());
	 }
}
    class Test
   {
     public static void main(String[] args)
    {
      System.out.println("main mehtod"+Thread.currentThread().getName());
      MyThread t0=new MyThread();       //0
      System.out.println(t0.getName());
   
      
      
      new MyThread().m1(); //1
      new B().m1();
     }
}
    
    class B
    {
    	void m1(){new MyThread().m1();System.out.println("class B"+Thread.currentThread().getName());}
    }
   
    class B1
   {
	   void m1()
	   {
		   new MyThread().m1();//4
           System.out.println();	  
	   }
   }
  
C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main mehtodmain
Thread-0
t--->Thread-2
t1--->Thread-3
MyThread m1main
t--->Thread-5
t1--->Thread-6
MyThread m1main
class Bmain

C:\Users\DELL\Desktop>

EXPLANATION:-
============
***************************-----END of--->13<--------***************************
Example=14
=========
NOTE:-
-----
PROGRAME=14
=========
class MyThread extends Thread
{
    public void run()
    {
    	System.out.println(Thread.currentThread().getPriority());
    	System.out.println(Thread.currentThread().getName());

    	MyThread t=new MyThread();
        t.m1();
    }	
         public void m1()
    {
    	System.out.println(Thread.currentThread().getPriority());
    	System.out.println(Thread.currentThread().getName());
    	new MyThread().m2();
    }
    
         public void m2()
         {
         	System.out.println(Thread.currentThread().getPriority());
         	System.out.println(Thread.currentThread().getName());
         }
}
class Test
{
  public static void main(String[] args) 
  {
	  
	MyThread t=new MyThread();
	t.start();
	t.setPriority(9);
  }	
}

C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
9
Thread-0
9
Thread-0
9
Thread-0

C:\Users\DELL\Desktop>
EXPLANATION:-
============

System.out.println(Thread.currentThread().getName());
   
 Assume  have written this line in method m1() method.
------->>>>

 run () method--->called by Thread 0
                  inside the run() method again creating one more Thread Object
				  MyThread t=new Mythread(); ---->Thread 1
				  t.m1();

				  so controls goes to m1() method and tries to execute this line
                  System.out.println(Thread.currentThread().getName());
				  
				  JVm figures out Thread 1 is calling m1 () method
                  But
				  whose is responsible for calling Thread 1 ....?
				  oh o o Thread 0 is responsible so Thread 0 will be printed.
				      

One more Assumption:- 
1)It prints Base Thread name responsible for calling the m1() method..

2)We cannot put same point on  main Thread when calling run() method..
                    Ex:- t.start()
					          --->calls run() method.
                         Inside the run method If we trying to print getName()
				        Base Thread name won t be printed..
						calling Thread name will be printed..





***************************-----END of--->14<--------***************************
Example=15
=========
NOTE:-
-----
PROGRAME=15
=========
Case 1:-
--------
class MyThread extends Thread{}

class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread();
	  System.out.println("MyThread t= "+t.getPriority());

  }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
MyThread t= 5

Case 2:-
-------
 class MyThread extends Thread
{
   public void run()
	   {
         
		 MyThread t1=new MyThread();
	     System.out.println("MyThread t1 in run method= "+t1.getPriority());
	  }
}

class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread();
	  System.out.println("MyThread t= "+t.getPriority());
	  t.start();

  }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
MyThread t= 5
MyThread t1 in run method= 5

Case 3:-
--------
class MyThread extends Thread
{
   public void run()
	   {
         
		 MyThread t1=new MyThread();
	     System.out.println("MyThread t1 in run method= "+t1.getPriority());
	  }
}

class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread();
	  t.setPriority(8);
	  System.out.println("MyThread t= "+t.getPriority());
	  t.start();


  }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
MyThread t= 8
MyThread t1 in run method= 8

Case:-4
-------
class MyThread extends Thread{}
class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread();
	  t.setPriority(11);
	  System.out.println("MyThread t= "+t.getPriority());
	  t.start();


  }	
}



C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
Exception in thread "main" java.lang.IllegalArgumentException
        at java.lang.Thread.setPriority(Thread.java:1086)
        at Test.main(Test.java:9)

C:\Users\DELL\Desktop>

EXPLANATION:-
============
***************************-----END of--->15<--------***************************
Example=16
=========
NOTE:-
-----
PROGRAME=16
=========
class MyThread extends Thread
{
   public void run()
	   {
         
		 MyThread t1=new MyThread();
	     System.out.println("MyThread t1 in run method= "+t1.getPriority());
	  }
}

class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread(); //Point:-1
	  System.out.println("MyThread t= "+t.getPriority());
	  t.start();
  }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
MyThread t= 5
MyThread t1 in run method= 5

EXPLANATION:-
============
Point :-1
---------
Who is responsible for executing/creating that Thread 
main Thread

so Parent is main Thread 
Child Thread is t


***************************-----END of--->16<--------***************************
Example=17
=========
NOTE:-
-----
PROGRAME=17
=========
class MyThread extends Thread
{
   public void run()
	   {
	     MyThread t1=new MyThread();
		 t1.setPriority(9);
	     System.out.println("MyThread t1 in run method= "+t1.getPriority());
	  }
}

class Test
{
  public static void main(String[] args) 
  {
	  System.out.println("main method priority "+Thread.currentThread().getPriority());
	  
	  MyThread t=new MyThread();
	  System.out.println("MyThread t= "+t.getPriority());
	  t.start();
  }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
MyThread t= 5
MyThread t1 in run method= 9

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->17<--------***************************
Example=18
=========
NOTE:-
-----
PROGRAME=18
=========
class MyThread extends Thread
{
}

class Test
{
  public static void main(String[] args) 
  {
	 System.out.println("main method priority "+Thread.currentThread().getPriority());
     Thread.currentThread().setPriority(10);
	 System.out.println("main method priority after changing "+Thread.currentThread().getPriority());

   }	
}



C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
main method priority after changing 10

EXPLANATION:-
============
***************************-----END of--->18<--------***************************
Example=19
=========
NOTE:-
-----
PROGRAME=19
=========
class MyThread extends Thread
{
}

class Test
{
  public static void main(String[] args) 
  {
	 System.out.println("main method priority "+Thread.currentThread().getPriority());
     Thread.currentThread().setPriority(15);
	 System.out.println("main method priority after changing "+Thread.currentThread().getPriority());

   }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
Exception in thread "main" java.lang.IllegalArgumentException
        at java.lang.Thread.setPriority(Thread.java:1086)
        at Test.main(Test.java:10)

C:\Users\DELL\Desktop>

EXPLANATION:-
============
***************************-----END of--->19<--------***************************
Example=20
=========
NOTE:-
-----
PROGRAME=20
=========
class MyThread extends Thread
{
}

class Test
{
  public static void main(String[] args) 
  {
	 System.out.println("main method priority "+Thread.currentThread().getPriority());
     Thread.currentThread().setPriority(7);
	 System.out.println("main method priority after changing "+Thread.currentThread().getPriority());
     MyThread t=new MyThread();
	 System.out.println("t Thread priority "+t.getPriority());
   }	
}


C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
main method priority after changing 7
t Thread priority 7

C:\Users\DELL\Desktop>
EXPLANATION:-
============
***************************-----END of--->20<--------***************************
Example=21
=========
NOTE:-
-----
PROGRAME=21
=========
class MyThread extends Thread
{
	public void run()
		{
     MyThread t1=new MyThread();
	 System.out.println("t1 Thread priority in run() method "+t1.getPriority());
 
	    }
}

class Test
{
  public static void main(String[] args) 
  {
	 System.out.println("main method priority "+Thread.currentThread().getPriority());
     Thread.currentThread().setPriority(7);
	 System.out.println("main method priority after changing "+Thread.currentThread().getPriority());
     MyThread t=new MyThread();//Point:-1
	 System.out.println("t Thread priority "+t.getPriority());
	 t.start();
   }	
}




C:\Users\DELL\Desktop>javac Test.java

C:\Users\DELL\Desktop>java Test
main method priority 5
main method priority after changing 7
t Thread priority 7
t1 Thread priority in run() method 7

C:\Users\DELL\Desktop>

EXPLANATION:-
============
Point:-1
MyThread t=new MyThread();
This line executed by main Thread so Parent is main Thread and Child is t Thread..
***************************-----END of--->21<--------***************************
Example=22
=========
NOTE:-
-----
PROGRAME=22
=========
class MyThread extends Thread
{
	public void run()
		 {
               for (int i=0;i<20;i++)
               {
                   System.out.println("Child Thread");
               }
		 }
}

class Test
{
  public static void main(String[] args) 
  {
       MyThread t=new MyThread();
	   t.setPriority(9);
       t.start();

              for (int i=0;i<20;i++)
               {
                   System.out.println("main Thread");
               }
   }	
}

C:\Users\DELL\Desktop>java Test
main Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
Child Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
Child Thread
Child Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread
main Thread


EXPLANATION:-
============
Here frist we have to get Child Thread and then main Thread
But we are not getting the exact output coz some 
OS/platforms will not support the priority regarding Thread.


so wats the remedy..?
use batch file,
To use batch file we must use licensed version of license.

some platforms won t support proper priority for Thread s.
***************************-----END of--->22<--------***************************
Example=23
=========
NOTE:-
-----
PROGRAME=23
=========
EXPLANATION:-
============
***************************-----END of--->23<--------***************************
Example=24
=========
NOTE:-
-----
PROGRAME=24
=========
EXPLANATION:-
============
***************************-----END of--->24<--------***************************
Example=25
=========
NOTE:-
-----
PROGRAME=25
=========
EXPLANATION:-
============
***************************-----END of--->25<--------***************************
Example=26
=========
NOTE:-
-----
PROGRAME=26
=========
EXPLANATION:-
============
***************************-----END of--->26<--------***************************
Example=27
=========
NOTE:-
-----
PROGRAME=27
=========
EXPLANATION:-
============
***************************-----END of--->27<--------***************************
Example=28
=========
NOTE:-
-----
PROGRAME=28
=========
EXPLANATION:-
============
***************************-----END of--->28<--------***************************
Example=29
=========
NOTE:-
-----
PROGRAME=29
=========
EXPLANATION:-
============
***************************-----END of--->29<--------***************************
Example=30
=========
NOTE:-
-----
PROGRAME=30
=========
EXPLANATION:-
============
***************************-----END of--->30<--------***************************
Example=31
=========
NOTE:-
-----
PROGRAME=31
=========
EXPLANATION:-
============
***************************-----END of--->31<--------***************************
Example=32
=========
NOTE:-
-----
PROGRAME=32
=========
EXPLANATION:-
============
***************************-----END of--->32<--------***************************
Example=33
=========
NOTE:-
-----
PROGRAME=33
=========
EXPLANATION:-
============
***************************-----END of--->33<--------***************************
Example=34
=========
NOTE:-
-----
PROGRAME=34
=========
EXPLANATION:-
============
***************************-----END of--->34<--------***************************
Example=35
=========
NOTE:-
-----
PROGRAME=35
=========
EXPLANATION:-
============
***************************-----END of--->35<--------***************************
Example=36
=========
NOTE:-
-----
PROGRAME=36
=========
EXPLANATION:-
============
***************************-----END of--->36<--------***************************
Example=37
=========
NOTE:-
-----
PROGRAME=37
=========
EXPLANATION:-
============
***************************-----END of--->37<--------***************************
Example=38
=========
NOTE:-
-----
PROGRAME=38
=========
EXPLANATION:-
============
***************************-----END of--->38<--------***************************
Example=39
=========
NOTE:-
-----
PROGRAME=39
=========
EXPLANATION:-
============
***************************-----END of--->39<--------***************************
Example=40
=========
NOTE:-
-----
PROGRAME=40
=========
EXPLANATION:-
============
***************************-----END of--->40<--------***************************
Example=41
=========
NOTE:-
-----
PROGRAME=41
=========
EXPLANATION:-
============
***************************-----END of--->41<--------***************************
Example=42
=========
NOTE:-
-----
PROGRAME=42
=========
EXPLANATION:-
============
***************************-----END of--->42<--------***************************
Example=43
=========
NOTE:-
-----
PROGRAME=43
=========
EXPLANATION:-
============
***************************-----END of--->43<--------***************************
Example=44
=========
NOTE:-
-----
PROGRAME=44
=========
EXPLANATION:-
============
***************************-----END of--->44<--------***************************
Example=45
=========
NOTE:-
-----
PROGRAME=45
=========
EXPLANATION:-
============
***************************-----END of--->45<--------***************************
Example=46
=========
NOTE:-
-----
PROGRAME=46
=========
EXPLANATION:-
============
***************************-----END of--->46<--------***************************
Example=47
=========
NOTE:-
-----
PROGRAME=47
=========
EXPLANATION:-
============
***************************-----END of--->47<--------***************************
Example=48
=========
NOTE:-
-----
PROGRAME=48
=========
EXPLANATION:-
============
***************************-----END of--->48<--------***************************
Example=49
=========
NOTE:-
-----
PROGRAME=49
=========
EXPLANATION:-
============
***************************-----END of--->49<--------***************************
Example=50
=========
NOTE:-
-----
PROGRAME=50
=========
EXPLANATION:-
============
***************************-----END of--->50<--------***************************
Example=51
=========
NOTE:-
-----
PROGRAME=51
=========
EXPLANATION:-
============
***************************-----END of--->51<--------***************************
Example=52
=========
NOTE:-
-----
PROGRAME=52
=========
EXPLANATION:-
============
***************************-----END of--->52<--------***************************
Example=53
=========
NOTE:-
-----
PROGRAME=53
=========
EXPLANATION:-
============
***************************-----END of--->53<--------***************************
Example=54
=========
NOTE:-
-----
PROGRAME=54
=========
EXPLANATION:-
============
***************************-----END of--->54<--------***************************
Example=55
=========
NOTE:-
-----
PROGRAME=55
=========
EXPLANATION:-
============
***************************-----END of--->55<--------***************************
Example=56
=========
NOTE:-
-----
PROGRAME=56
=========
EXPLANATION:-
============
***************************-----END of--->56<--------***************************
Example=57
=========
NOTE:-
-----
PROGRAME=57
=========
EXPLANATION:-
============
***************************-----END of--->57<--------***************************
Example=58
=========
NOTE:-
-----
PROGRAME=58
=========
EXPLANATION:-
============
***************************-----END of--->58<--------***************************
Example=59
=========
NOTE:-
-----
PROGRAME=59
=========
EXPLANATION:-
============
***************************-----END of--->59<--------***************************
Example=60
=========
NOTE:-
-----
PROGRAME=60
=========
EXPLANATION:-
============
***************************-----END of--->60<--------***************************
Example=61
=========
NOTE:-
-----
PROGRAME=61
=========
EXPLANATION:-
============
***************************-----END of--->61<--------***************************
Example=62
=========
NOTE:-
-----
PROGRAME=62
=========
EXPLANATION:-
============
***************************-----END of--->62<--------***************************
Example=63
=========
NOTE:-
-----
PROGRAME=63
=========
EXPLANATION:-
============
***************************-----END of--->63<--------***************************
Example=64
=========
NOTE:-
-----
PROGRAME=64
=========
EXPLANATION:-
============
***************************-----END of--->64<--------***************************
Example=65
=========
NOTE:-
-----
PROGRAME=65
=========
EXPLANATION:-
============
***************************-----END of--->65<--------***************************
Example=66
=========
NOTE:-
-----
PROGRAME=66
=========
EXPLANATION:-
============
***************************-----END of--->66<--------***************************
Example=67
=========
NOTE:-
-----
PROGRAME=67
=========
EXPLANATION:-
============
***************************-----END of--->67<--------***************************
Example=68
=========
NOTE:-
-----
PROGRAME=68
=========
EXPLANATION:-
============
***************************-----END of--->68<--------***************************
Example=69
=========
NOTE:-
-----
PROGRAME=69
=========
EXPLANATION:-
============
***************************-----END of--->69<--------***************************
Example=70
=========
NOTE:-
-----
PROGRAME=70
=========
EXPLANATION:-
============
***************************-----END of--->70<--------***************************
Example=71
=========
NOTE:-
-----
PROGRAME=71
=========
EXPLANATION:-
============
***************************-----END of--->71<--------***************************
Example=72
=========
NOTE:-
-----
PROGRAME=72
=========
EXPLANATION:-
============
***************************-----END of--->72<--------***************************
Example=73
=========
NOTE:-
-----
PROGRAME=73
=========
EXPLANATION:-
============
***************************-----END of--->73<--------***************************
Example=74
=========
NOTE:-
-----
PROGRAME=74
=========
EXPLANATION:-
============
***************************-----END of--->74<--------***************************
Example=75
=========
NOTE:-
-----
PROGRAME=75
=========
EXPLANATION:-
============
***************************-----END of--->75<--------***************************
Example=76
=========
NOTE:-
-----
PROGRAME=76
=========
EXPLANATION:-
============
***************************-----END of--->76<--------***************************
Example=77
=========
NOTE:-
-----
PROGRAME=77
=========
EXPLANATION:-
============
***************************-----END of--->77<--------***************************
Example=78
=========
NOTE:-
-----
PROGRAME=78
=========
EXPLANATION:-
============
***************************-----END of--->78<--------***************************
Example=79
=========
NOTE:-
-----
PROGRAME=79
=========
EXPLANATION:-
============
***************************-----END of--->79<--------***************************
Example=80
=========
NOTE:-
-----
PROGRAME=80
=========
EXPLANATION:-
============
***************************-----END of--->80<--------***************************
Example=81
=========
NOTE:-
-----
PROGRAME=81
=========
EXPLANATION:-
============
***************************-----END of--->81<--------***************************
Example=82
=========
NOTE:-
-----
PROGRAME=82
=========
EXPLANATION:-
============
***************************-----END of--->82<--------***************************
Example=83
=========
NOTE:-
-----
PROGRAME=83
=========
EXPLANATION:-
============
***************************-----END of--->83<--------***************************
Example=84
=========
NOTE:-
-----
PROGRAME=84
=========
EXPLANATION:-
============
***************************-----END of--->84<--------***************************
Example=85
=========
NOTE:-
-----
PROGRAME=85
=========
EXPLANATION:-
============
***************************-----END of--->85<--------***************************
Example=86
=========
NOTE:-
-----
PROGRAME=86
=========
EXPLANATION:-
============
***************************-----END of--->86<--------***************************
Example=87
=========
NOTE:-
-----
PROGRAME=87
=========
EXPLANATION:-
============
***************************-----END of--->87<--------***************************
Example=88
=========
NOTE:-
-----
PROGRAME=88
=========
EXPLANATION:-
============
***************************-----END of--->88<--------***************************
Example=89
=========
NOTE:-
-----
PROGRAME=89
=========
EXPLANATION:-
============
***************************-----END of--->89<--------***************************
Example=90
=========
NOTE:-
-----
PROGRAME=90
=========
EXPLANATION:-
============
***************************-----END of--->90<--------***************************
Example=91
=========
NOTE:-
-----
PROGRAME=91
=========
EXPLANATION:-
============
***************************-----END of--->91<--------***************************
Example=92
=========
NOTE:-
-----
PROGRAME=92
=========
EXPLANATION:-
============
***************************-----END of--->92<--------***************************
Example=93
=========
NOTE:-
-----
PROGRAME=93
=========
EXPLANATION:-
============
***************************-----END of--->93<--------***************************
Example=94
=========
NOTE:-
-----
PROGRAME=94
=========
EXPLANATION:-
============
***************************-----END of--->94<--------***************************
Example=95
=========
NOTE:-
-----
PROGRAME=95
=========
EXPLANATION:-
============
***************************-----END of--->95<--------***************************
Example=96
=========
NOTE:-
-----
PROGRAME=96
=========
EXPLANATION:-
============
***************************-----END of--->96<--------***************************
Example=97
=========
NOTE:-
-----
PROGRAME=97
=========
EXPLANATION:-
============
***************************-----END of--->97<--------***************************
Example=98
=========
NOTE:-
-----
PROGRAME=98
=========
EXPLANATION:-
============
***************************-----END of--->98<--------***************************
Example=99
=========
NOTE:-
-----
PROGRAME=99
=========
EXPLANATION:-
============
***************************-----END of--->99<--------***************************
Example=100
=========
NOTE:-
-----
PROGRAME=100
=========
EXPLANATION:-
============
***************************-----END of--->100<--------***************************
